### ISSUE TITLE
Possibility to restrict ViewSet actions?

### ISSUE THREAD

**Issue by jole78** [AltSchool/dynamic-rest#126]
First of all, this package seems very promising and maybe I´m just misunderstanding how it works...but:

Is there a possibility to restrict which ViewSet actions that the DynamicViewSet class exposes? Basically I would just like to make use of the include feature on one of my current ViewSet actions (e.g. retrieve). As I understand I would need your Serializer, Viewset, and Router to make this work? And that would make my current ViewSet (DRF) a complete CRUD ViewSet which is not what I want since it currently only holds the retrieve action.

In my example I´m fetching a User object and I would like to expand (include) the relationship that the user has to its set of permissions and groups...just that, nothing more (at the moment at least).

**Comment by ryochiji** [comment]
If I understand correctly, you'd like to create a ViewSet that supports retrieval operations but not create, update and delete operations?

If that's what you're looking for, something like this should work:

```python
class MyReadOnlyViewSet(DynamicViewSet):
# usual viewset boilerplate here

    def create(self, request, *args, **kwargs):
        return Response("Read only", status=405)

    def update(self, request, *args, **kwargs):
        return Response("Read only", status=405)

    def destroy(self, request, *args, **kwargs):
        return Response("Read only", status=405)
```

You can also turn that into a mixin and add it to viewsets that you want to make read-only.

**Comment by jole78** [comment]
Ah, got it. I'll try that thanks. Maybe this could make its way into the framework?? As a mixin or as a separate ViewSet class (like the DRF has...).
