### ISSUE TITLE
return structure of DynamicSortingFilter.get_valid_fields does not match djangorestframework's OrderingFilter.get_valid_fields

### ISSUE THREAD

**Issue by ornoone** [AltSchool/dynamic-rest#138]
hi, 

I found a bug if make a search with a field that does not exists in the serializer : ``/?filter{fieldnotinserializer}=val``. 

ValueError: too many values to unpack

it seem that the signature of DynamicSortingFilter.get_valid_fields does not match his parent class's.
the original result from django-rest-framework is a list of 2n tuple, but you return a list of 3n tuple. 

it seem that this broke the OrderingFilter.get_template_context method since the commit aeb57913c9f2a7ad1ffc1db825c3e6f44b4818ee of restframowork which do no longer pass the result of get_valid_fields but iterate over it instead. 

this happen by browsing the django-rest-framework interface

version used : 

- djangorestframework==3.4.0
- dynamic-rest==1.5.0

**Comment by aleontiev** [comment]
@ornoone thanks for reporting this issue. I've changed the return value for compatibility in #140, but I'm having trouble actually reproducing on DREST master with DRF 3.4.0; can you provide further details as to how you triggered this error? Was this in the browsable API (format=api) or the admin API (format=admin)? Which endpoint?

**Comment by ornoone** [comment]
hi, thanks for the fix. sorry, but the endpoint used durring the bug is a customized subclass of BrowsableAPIRenderer that remove the form renderer for performance reasons. 

sorry, but for now, my branch that triggered the bug is dead and I don't have the context I had. 

your fix seem pretty good to me. I hope I will go back to my previous work and try your fix in the next week.
