### ISSUE TITLE
Can you guys update pypi version?

### ISSUE THREAD

**Issue by legshort** [AltSchool/dynamic-rest#149]
I saw the latest version is v1.5.7, howerver, the latest version I can install from pip command is v1.5.0.
I would appreciate if you update pypi version, thanks!

**Comment by legshort** [comment]
Self Answer

This command installs DREST with latest commit and also pip freeze builds based on this commit.
```shell
pip install -e git+https://github.com/AltSchool/dynamic-rest.git#egg=dynamic_rest
```

Reference: http://stackoverflow.com/a/20460931/2951749

**Comment by kciredor** [comment]
+1 please release a new pypi version, as a team we wan't to ditch all the -e type of installs.

**Comment by ddaan** [comment]
+1 :) Is there anything I can do to help?

**Comment by aleontiev** [comment]
1.5.7 is now on PyPi: https://pypi.python.org/pypi/dynamic-rest/1.5.7
