### ISSUE TITLE
Version 1.6.6 not available in pypi

### ISSUE THREAD

**Issue by dpaluch-rp** [AltSchool/dynamic-rest#170]
Hi, 
the latest relased version on pypi is 1.6.4

Can you update package?

Best wishes,
Darek

**Comment by auvipy** [comment]
exactly. django 1.11.1 and drf 3.6.3 based version on pypi would be really great

**Comment by aleontiev** [comment]
Uploaded 1.6.6 to PyPi, will try to be more diligent about uploading ASAP going forward. Thanks for the reminder guys :)

**Comment by auvipy** [comment]
try to automate the process if possible :) amazing package btw

**Comment by aleontiev** [comment]
Thanks, glad you're getting value out of it!

We currently have a set of Makefile commands that take care of distribution (e.g. `make pypi_upload` will push the current version provided you have the PyPi credentials). I can see us moving this out to CI for a more automated process.
