### ISSUE TITLE
Install 1.6.6 pypi package downgrade django from 1.11.1 to 1.11

### ISSUE THREAD

**Issue by dpaluch-rp** [AltSchool/dynamic-rest#172]
Hi,
like in subject `pip3 install dynamic_rest` downgrade django version to bugged 1.11 version.

**Comment by masterfloda** [comment]
It works fine with 1.11.2 and passes all tests.
Should the requirements be updated to `Django==1.11.2` or `Django>1.11`?

**Comment by aleontiev** [comment]
I've just updated requirement to `Django<1.12` (assuming all patches to 1.11 will work) and tox to test 1.11.2
