### ISSUE TITLE
DRF renderers ignored

### ISSUE THREAD

**Issue by masterfloda** [AltSchool/dynamic-rest#177]
https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/viewsets.py#L78 overrides the `REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES']` setting. Why? Also, why is there a DYNAMIC_REST setting to disable the browsable API?
I think the easier solution would be using the DRF settings. To enable the dynamic browsable API, just add it to these settings. Like:

```python
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'dynamic_rest.renderers.DynamicBrowsableAPIRenderer',
        'myproject.renderers.MyRenderer',
    ),
```

**Comment by aleontiev** [comment]
:+1: to removing `renderer_classes`. Can you submit a PR?

The setting to disable the browsable API is meant to be used in production environments where performance of the browsable API could be an issue

**Comment by masterfloda** [comment]
Wow, that was a fast reply :-) I'm just working on the PR.
To disable the browsable API in prod makes total sense. But that can also be done with the `DEFAULT_RENDERER_CLASSES`.

I like to split my settings by environment. So here's two ways to do it:

settings/base.py

```python
# dynamic_rest way to do it
DYNAMIC_REST = {
    'ENABLE_BROWSABLE_API': False, 
}

# DRF way to do it
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'myproject.renderers.MyRenderer',
    ],
}
```

settings/dev.py

```python
# dynamic_rest way to do it
DYNAMIC_REST['ENABLE_BROWSABLE_API'] = True 

# DRF way to do it
REST_FRAMEWORK ['DEFAULT_RENDERER_CLASSES'].append('dynamic_rest.renderers.DynamicBrowsableAPIRenderer')
```

**Comment by aleontiev** [comment]
@masterfloda that makes sense, but I would like to keep `ENABLE_BROWSABLE_API` since this is an additive feature that does not interfere with DRF settings in default configuration (unlike the `viewset.renderer_classes` override). I do think we should remove the explicit override of `renderer_classes` at the viewset level.
