### ISSUE TITLE
Allow only specific methods with DynamicModelViewSet

### ISSUE THREAD

**Issue by ses4j** [AltSchool/dynamic-rest#188]
Sometimes views allow certain methods and not others.  You can whitelist the ones you want in DRF with, for instance:

```
class MyView(
        mixins.UpdateModelMixin,
        viewsets.GenericViewSet):
```

instead of using `ModelViewSet` which incorporates all actions.

How would you replicate this with a DynamicViewSet?

**Comment by aleontiev** [comment]
You can use [this mixin](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/viewsets.py#L56) to accomplish the same thing.

**Comment by ses4j** [comment]
@aleontiev thanks for responding.  I saw that in looking through the code, but there's a bunch of code directly on `DynamicModelViewSet` which I'd be losing out on -- I didn't study what was in there, but figured I'd be losing _something_...
