### ISSUE TITLE
Please release version 1.6.8 on PyPi

### ISSUE THREAD

**Issue by sp1ky** [AltSchool/dynamic-rest#195]
Hi,

Can you release 1.6.8 to PyPi please, @aleontiev? The fix in [bcf9c6cf4a5e2d740b3526a1af75a00ceea419de](https://github.com/AltSchool/dynamic-rest/commit/bcf9c6cf4a5e2d740b3526a1af75a00ceea419de) is not released so I'm getting:

`ContextualVersionConflict: (Django 1.11.5, Requirement.parse('Django<=1.11,>=1.8'), set(['dynamic-rest']))`

Thanks!

**Comment by auvipy** [comment]
i think it should be 1.6.9
