### ISSUE TITLE
No support for multiple filters against the same field

### ISSUE THREAD

**Issue by benhawes** [AltSchool/dynamic-rest#213]
Multiple values for the same filter do not seem to be supported; eg. if my query looks like this: `?filter{-option}=value1&filter{-option}=value2` to exclude two different values from the results, only the first is respected.

**Comment by ryochiji** [comment]
Try using the `.in` operator, e.g. `?filter{-option.in}=value1&filter{-option.in}=value2`. I don't recall for sure whether that works for exclusion filters but let me know if that works.

**Comment by benhawes** [comment]
That does seem to indeed - thank you, that would never have occurred to me!
