### ISSUE TITLE
dynamic_rest.patches.patch_prefetch_one_level - too many values to unpack

### ISSUE THREAD

**Issue by ben-prezola** [AltSchool/dynamic-rest#221]
Django==2.0.3
DRF==3.7.7

The `dynamic_rest.patches.patch_prefetch_one_level` patch is incompatible.

prefetcher.get_prefetch_queryset returns `ValueError: too many values to unpack (expected 5)`

**Comment by lexuses** [comment]
Сaught the same error. Try to switch version to master or reinstall dynamic-rest lib with @master branch.

**Comment by ben-prezola** [comment]
Thanks

**Comment by ryochiji** [comment]
Just released 1.8.0 which adds support for Django 2.0 and DRF 3.7.
