### ISSUE TITLE
Are embedded relationships less performant than sideloaded relationships query-wise?

### ISSUE THREAD

**Issue by simkimsia** [AltSchool/dynamic-rest#228]
I know that embedded relationships is more likely to produce a bigger payload than sideloaded ones as explained here at https://github.com/AltSchool/dynamic-rest#embedded-relationships

My question is whether the performance of the query is also not as good for embedded relationships compared to sideloaded ones?

**Comment by aleontiev** [comment]
From a query perspective, there is no difference between an embedded and sideloaded relationship. 

Sideloading happens as a post-processing step after an embedded representation has been constructed. Therefore, a sideloaded representation will take up potentially less space, at the cost of a bit more processing time (should be negligible compared to query times)

**Comment by simkimsia** [comment]
Thanks for reply. Apologies that I have missed this. 

If I use sideloaded, then it's important that the sideloaded entities are using their natural id in as the array index, otherwise, it can be hard at the client frontend to traverse. 

Is there a drest way to do this?

E.g. in the documentation https://dynamic-rest.readthedocs.io/en/latest/tutorial.html#serializer-with-relations

there's an example url like `http://localhost:9002/events/?include[]=users.*` which sideloads the users

the payload will usually have 
{
  "events:[
     {
        "name": "new event!",
        "status": "current",
        "location": 2,
        "users": [1,2]
    },...],
   "users": [
       {"username": "alice", id:1},
       {"username": "bob", id:2}
    ]
}


So I was thinking whether might be easier to get back as
{
  "events:[
     {
        "name": "new event!",
        "status": "current",
        "location": 2,
        "users": [1,2]
    },...],
   "users": {
       "1":{"username": "alice", id:1},
       "2":{"username": "bob", id:2}
    }
}

Right now, my workaround is simply use embed

**Comment by ryochiji** [comment]
@simkimsia - Yeah, I can see how that could be easier to parse (we use Ember Data ourselves, which has an understanding of the models so is able to stitch together the data).

One way you can override the sideloading format would be to [override ListSerializer](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/serializers.py#L92) to use your own processor (maybe a slight modification of the default [SideloadingProcessor](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/processors.py#L44)), and then use the [`LIST_SERIALIZER_CLASS` config](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/conf.py#L42) to replace the default ListSerializer.

**Comment by simkimsia** [comment]
Thanks @ryochiji
