### ISSUE TITLE
Not compatible with DRF 3.8.2

### ISSUE THREAD

**Issue by soccer99** [AltSchool/dynamic-rest#246]
Getting import error

`cannot import name 'replace_methodname'`

**Comment by humitos** [comment]
Hi! Is there a plan to support DRF >3.8? I'm considering to use this package, but we are on DRF 3.9.1 at the moment. Thanks!

**Comment by joshvillbrandt** [comment]
I tried to update to DRF 3.9.1 today because Github has started reporting a vulnerability on older versions of DRF.

> [WS-2019-0037](https://github.com/encode/django-rest-framework/commit/75a489150ae24c2f3c794104a8e98fa43e2c9ce9) (moderate severity)
> Vulnerable versions: < 3.9.1
> Patched version: 3.9.1
> Django-Rest-Framework, before 3.9.1, has a XSS vulnerability caused by disabled autoescaping in the default DRF Browsable API view templates.

**Comment by ryochiji** [comment]
DRF 3.9 is officially supported with v1.9.5
