### ISSUE TITLE
pypi hasn't updated to the lastest v1.9

### ISSUE THREAD

**Issue by simkimsia** [AltSchool/dynamic-rest#268]
I have issues updating to the latest v1.9 and I need that because I have to override the list_serializer_class

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/245021/49363059-9b828500-f71b-11e8-8108-b2f5f2af1ee7.png">
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/245021/49363067-a1786600-f71b-11e8-80f5-01fb833a26a0.png">

**Comment by simkimsia** [comment]
For those who need a workaround, replace this in your `requirements.txt`

Originally  
```
dynamic-rest==1.9.3 # https://github.com/AltSchool/dynamic-rest
```

Use this to directly download from github
```
-e git+https://github.com/AltSchool/dynamic-rest.git@v1.9.3#egg=dynamic-rest
```

Also if you use docker then you need to ensure you have installed git

**Comment by ryochiji** [comment]
Pushed v1.9.4.
