### ISSUE TITLE
Please run tests against Python 3.6 and 3.7

### ISSUE THREAD

**Issue by stardust85** [AltSchool/dynamic-rest#277]
I believe they will pass anyway 👍 Is it enough to add them to tox.ini and Readme.rst, or are there some other places?

**Comment by stardust85** [comment]
I found 3 related PRs:

- https://github.com/AltSchool/dynamic-rest/pull/254
- https://github.com/AltSchool/dynamic-rest/pull/276
- https://github.com/AltSchool/dynamic-rest/pull/259

**Comment by ryochiji** [comment]
Now included in v1.9.4 which has been pushed to PyPI.

**Comment by ryochiji** [comment]
Actually, still need to add tests for Py 3.7. Reopening.

**Comment by simkimsia** [comment]
https://github.com/AltSchool/dynamic-rest/releases/tag/v1.9.5 now supports this. U can close this
