### ISSUE TITLE
PrimaryKeyRelatedField

### ISSUE THREAD

**Issue by b14cknc0d3** [AltSchool/dynamic-rest#285]
**This is previously that i used ModelSerializer**
    `class UserSerializer(serializers.ModelSerializer):
	
	saledatas =serializers.PrimaryKeyRelatedField(many=True,queryset=Saledata.objects.all())
	    class Meta:
		    model = User
		    fields = ('id','username','saledatas')`
**How to call nested field like PrimaryKeyRelatedField above in DynamicModelSerializer**

    `AttributeError: saledatas is not a valid field for <class 'django.contrib.auth.models.User'>
   `

**Comment by aleontiev** [comment]
@b14cknc0d3 you would use a `DynamicRelationField` instead of `PrimaryKeyRelatedField` -- `DynamicRelationField` can flexibly render as either an ID or a relationship (see https://github.com/AltSchool/dynamic-rest#features)
