### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by neilfrndes** [AltSchool/dynamic-rest#294]
Is supporting[ Django 3](https://docs.djangoproject.com/en/3.0/releases/3.0/) in the pipeline?

**Comment by neilfrndes** [comment]
I got dynamic rest to work with Django 3 by replacing the django.utils.six import to the six library. 

I am happy to work on a PR to make dynamic rest compatible with Django 3 but I want to know from an expert is if replacing the six import is the biggest change needed. Moreover, since python 2.7 is soon approaching EOL, does it make sense to keep the six imports?

**Comment by amandeep-r** [comment]
I can help make it compatible with django 3 but I also don't know if replacing the six import is the the biggest change needed

**Comment by wlisesrivas** [comment]
@amandeep-r try fixing the `six` import first.

**Comment by to-bee** [comment]
Any updates here?

**Comment by suavesav** [comment]
@neilfrndes Please feel free to make a PR for this. We are working on deprecating py2 support, but for now we'll keep six around. Thanks!

**Comment by MikeBlomm** [comment]
Any progress on this? Django 3 has been out for a while now, and Python 2 is also EOL.

**Comment by amandeep-r** [comment]
So I made a fork where I replaced all calls to `from django.utils import six` with `import six` and it's working for me.

**Comment by creyD** [comment]
As #307 is merged, can this be closed as well?

**Comment by amandeep-r** [comment]
Does this fix warrant a new release?

**Comment by joshvillbrandt** [comment]
Would love this to be included in a release! Thanks!

**Comment by ErnestoFGonzalez** [comment]
I noticed there hasn't been much activity on this organisation's repos. Probably there won't be no more -- [I think they closed](https://www.edsurge.com/news/2021-01-15-the-edtech-company-formerly-known-as-altschool-sold-its-tech-so-what-s-left).

In the meantime I forked and **released a version that supports Django 3** under [django-dynamic-rest](https://pypi.org/project/django-dynamic-rest/). Feel free to make contributions there.

**Comment by ArnSch** [comment]
We're alive and kicking, most of our work is in private repos right now though. Really appreciate the work on django-dynamic-rest @ErnestoFGonzalez

**Comment by ErnestoFGonzalez** [comment]
Hey @ArnSch. Thanks for the response. Cool to hear you guys are still alive. 

Let me know if you'd like me help out with contributions in this repo and releases for `dynamic-rest` to avoid having users migrate. My email is ernesto@hunchat.com

**Comment by suavesav** [comment]
Released, thanks to @ErnestoFGonzalez and @chdastolfo
