### ISSUE TITLE
Update inflection library  to latest version 0.4.0

### ISSUE THREAD

**Issue by simkimsia** [AltSchool/dynamic-rest#301]
see #300 for the PR

**Comment by suavesav** [comment]
Hi @simkimsia, is there any particular reason for this other than keeping up to date?

aka is it blocking in any way?

**Comment by simkimsia** [comment]
Django 2.2 appears to use the latest inflector

So when I build my docker it gives a warning ⚠️ 

Is it blocking? No

But I like the warning in my docker build to go away

**Comment by suavesav** [comment]
sounds good, i'll test and merge it prior to the next release. Thanks for the PR

**Comment by simkimsia** [comment]
Just asking. Not in a hurry. Is the PR #300 ok to be merged?

Thank you

**Comment by simkimsia** [comment]
Any issues with https://github.com/AltSchool/dynamic-rest/pull/305, @suavesav ?
