### ISSUE TITLE
dynamic-rest incompatible with latest drf >=3.12.x (with fix for security vulnerability)

### ISSUE THREAD

**Issue by shivambol** [AltSchool/dynamic-rest#315]
Hi,
 
Our application has the requirements on - `djangorestframework` and `dynamic-rest`.
`djangorestframework >= 3.11.2` has a security fix as per the [release notes](https://www.django-rest-framework.org/community/release-notes/#3112)

dynamic-rest has a dependency on `djangorestframework` but only [supports version `<= 3.10`](https://pypi.org/project/dynamic-rest/)

Now if we downgrade our drf, our security checks fail due to the [security vulnerability ](https://www.django-rest-framework.org/community/release-notes/#3112)
and if we upgrade our drf to get around the security issue, dynamic-rest fails at runtime.

We have effectively reached _**dependency-hell.**_

Can the team please look into supporting `drf >= 3.12`

Thanks!

**Comment by suavesav** [comment]
resolved in latest release
