### ISSUE TITLE
Loosening and updating requirements for djangorestframework

### ISSUE THREAD

**Issue by OmenApps** [AltSchool/dynamic-rest#332]
[install_requires.txt](https://github.com/AltSchool/dynamic-rest/blob/master/install_requires.txt) currently requires `djangorestframework>=3.11.0,<=3.12.4`, but it is not clear where this requirement (to the minor version number X.X.X) comes from.

[Per the DRF docs](https://www.django-rest-framework.org/community/release-notes/#versioning), "Medium version numbers (0.x.0) may include API changes", so best policy, if the requirements are based on concerns for keeping with consistent api versions would be something like `djangorestframework>=3.11.0,<3.13.0`

But at this point it might be best to also update to allow the 3.13.X versions, since there are no significant API changes from the 3.12.X version. (The changes included in 3.13.0 can be found [here](https://www.django-rest-framework.org/community/release-notes/#3130))

I recommend modifying the requirement in install_requires.txt to `djangorestframework>=3.11.0,<3.14.0`.

**Comment by suavesav** [comment]
Resolved in #334
