### ISSUE TITLE
Limited set of features

### ISSUE THREAD

**Issue by mdefeche** [AltSchool/dynamic-rest#346]
Hello,

We have an existing API with filtering, sorting and pagination already set up but are interested in some of the serializer capabilities that this library offers (mainly embedded relationships). 

Is it possible to use a limited set of features ? Would overriding `WithDynamicViewSetMixin` with a limited set of feature work ?

Thanks

**Comment by aleontiev** [comment]
Hi @mdefeche you can set `featutes` on each viewset in case you want to disable any of the features (which are the parameters/groups `include[]`, `exclude[]`, `sort[]`, `filter{}` , etc)
