### ISSUE TITLE
How to negate a filter query? 

### ISSUE THREAD

**Issue by ridoo** [AltSchool/dynamic-rest#355]
I want to filter data via DREST but want to exclude content having a particular attribute value. For example like so:

`<url>/?filter{attribute.ne}}=bar`

```
{
  id: "foo",
  attribute: "bar"
}
```

However, I saw that there is no operator `ne` defined here:

https://github.com/AltSchool/dynamic-rest/blob/ed69e5af4ddf153e6eb304b7db80cc6adbf4d654/dynamic_rest/filters.py#L190-L213

All of these filters are "positive" filters. Also, in the docs I have not found any reference to negate a query. Do I miss something?

**Comment by ridoo** [comment]
Any hints on this one? perhaps I am missing something essential here

**Comment by ryochiji** [comment]
The [docs](https://github.com/AltSchool/dynamic-rest/tree/ed69e5af4ddf153e6eb304b7db80cc6adbf4d654#filtering) cover this but prepend the attribute name with `-`, e.g. `filter{-attribute}=bar`.

**Comment by ridoo** [comment]
@ryochiji interesting .. too simple to spot it :see_no_evil: Thanks! I will close this then.
